services:
  - type: web
    name: portail-etudiant
    runtime: docker
    plan: free
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: "Portail Etudiant"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://portail-etudiant.onrender.com   # update after first deploy
      - key: APP_LOCALE
        value: fr
      - key: APP_FALLBACK_LOCALE
        value: fr
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: FILESYSTEM_DISK
        value: local
      - key: BCRYPT_ROUNDS
        value: 12
